sudo: required
services:
  - docker

before_install:
  - docker build -t pritamkhose/docker-react -f Dockerfile.dev .

script:
  - docker run pritamkhose/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "DockerReact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-985964210512"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

